/* ============================================================
   Av. Arb. Selim Yalçın — site data + translations (TR / EN)
   ============================================================ */

window.SITE = {
  brand: {
    name: "Selim Yalçın",
    role: { tr: "Avukat & Arabulucu", en: "Attorney & Mediator" },
    initials: "SY",
    estd: "EST. 2013",
  },
  contact: {
    email: "avselimyalcin@gmail.com",
    phone: "+90 (216) 000 00 00",
    address: { tr: "Cevizli Mah. Kastamonu Sok. No:27-29 D:10\nKartal / İstanbul", en: "Cevizli Mah. Kastamonu Sok. No:27-29 D:10\nKartal / Istanbul" },
    instagram: "@avselimyalcin",
    hours: { tr: "Pazartesi – Cuma · 09:00–18:30\nCumartesi · Randevu ile", en: "Monday – Friday · 09:00–18:30\nSaturday · By appointment" },
  },
};

window.NAV = [
  { id: "home", path: "/", labelTR: "Ana Sayfa", labelEN: "Home" },
  { id: "ozgecmis", path: "/ozgecmis", labelTR: "Özgeçmiş", labelEN: "Profile" },
  { id: "arabuluculuk", path: "/arabuluculuk", labelTR: "Arabuluculuk", labelEN: "Mediation" },
  { id: "avukatlik", path: "/avukatlik", labelTR: "Avukatlık", labelEN: "Legal Counsel" },
  { id: "ucret-hesaplama", path: "/ucret-hesaplama", labelTR: "Ücret Hesaplama", labelEN: "Fee Calculator" },
  { id: "uygulamalar", path: "/uygulamalar", labelTR: "Uygulamalar", labelEN: "Applications" },
  { id: "blog", path: "/blog", labelTR: "Yazılar", labelEN: "Notes" },
  { id: "iletisim", path: "/iletisim", labelTR: "İletişim", labelEN: "Contact" },
];

window.T = {
  tr: {
    // Header
    appointment: "Randevu Al",
    menu: "Menü",
    close: "Kapat",

    // Home
    hero_eyebrow: "İstanbul · Hukuk Bürosu",
    hero_role: "Avukat & Arabulucu",
    hero_first: "Av. Arb. Selim",
    hero_last: "Yalçın",
    hero_phrase_pre: "Mahkemeden önce",
    hero_phrase_em: "uzlaşı",
    hero_phrase_post: "; mahkemede titiz savunma.",
    hero_meta_a: "Sicil",
    hero_meta_a_v: "İst. Barosu · 46524",
    hero_meta_b: "Arabulucu",
    hero_meta_b_v: "ADB · 26722",
    hero_meta_c: "Konum",
    hero_meta_c_v: "Kartal / İstanbul",
    hero_lede:
      "Bireyler ve şirketler için modern, etkin ve sonuç odaklı hukuki danışmanlık. Uyuşmazlıkları mahkeme öncesi çözüme kavuşturuyor; gerektiğinde dava süreçlerinde yanınızda oluyoruz.",
    hero_cta_primary: "Ön görüşme talep et",
    hero_cta_secondary: "Uzmanlık alanları",

    services_eyebrow: "Hizmet alanları",
    services_title: "Her uyuşmazlığa göre özelleştirilmiş yaklaşım.",
    services_sub: "Aile hukukundan ticari uyuşmazlıklara, iş hukukundan tüketici hukukuna geniş bir yelpazede uzman destek.",

    process_eyebrow: "Çalışma yöntemi",
    process_title: "Şeffaf, ölçülü, sonuç odaklı.",

    quote: "“Hukukun amacı, gücü dengelemek; iyi bir avukatın amacı, müvekkilinin sesini netleştirmektir.”",
    quote_attr: "Av. Arb. Selim Yalçın",

    cta_eyebrow: "İletişim",
    cta_title: "Hukuki sürecinize bugün başlayın.",
    cta_sub: "Yüzyüze ve online ön görüşme — aynı gün dönüş.",
    cta_primary: "Randevu al",

    // Özgeçmiş
    cv_eyebrow: "Özgeçmiş",
    cv_title: "Av. Arb. Selim Yalçın",
    cv_subtitle: "Avukat ve Arabulucu · İstanbul Barosu",
    cv_about_h: "Hakkımda",
    cv_about: [
      "2012 yılında Koç Üniversitesi Hukuk Fakültesi mezunu olup 2013 yılında avukatlık ruhsatını alarak meslek hayatına başladım.",
      "İstanbul Barosu'na 46524 sicil numarası ile kayıtlı olarak avukatlık faaliyetlerimi sürdürmekteyim.",
      "2018 yılında Koç Üniversitesi Özel Hukuk Tezli Yüksek Lisans programını tamamlayarak Ticaret Hukuku alanında uzmanlaştım.",
      "Mesleki kariyerim boyunca Ticaret Hukuku başta olmak üzere Aile Hukuku, Borçlar Hukuku, İcra ve İflas Hukuku ile Ceza Hukuku alanlarında aktif olarak çalışmaktayım.",
      "2023 yılı itibarıyla 26722 sicil numarası ile arabuluculuk siciline kayıtlı olup arabuluculuk faaliyetleri de yürütmekteyim.",
      "İleri düzeyde İngilizce ve başlangıç seviyesinde Almanca bilmekteyim.",
    ],
    cv_education_h: "Eğitim",
    cv_education: [
      ["Koç Üniversitesi", "Özel Hukuk Tezli Yüksek Lisans", "2018"],
      ["Koç Üniversitesi", "Hukuk Fakültesi", "2012"],
      ["University of Connecticut", "İngilizce Dil Okulu", "2006"],
    ],
    cv_memberships_h: "Üyelikler",
    cv_memberships: ["İstanbul Barosu", "Adalet Bakanlığı Arabuluculuk Daire Başkanlığı"],
    cv_certs_h: "Sertifikalar",
    cv_certs: ["Ticaret Hukuku", "Ceza Hukuku", "Aile Hukuku", "Borçlar Hukuku", "İcra-İflas Hukuku"],
    cv_specs_h: "Uzmanlık alanları",
    cv_specs: ["Ticaret Hukuku", "Aile Hukuku", "İş Hukuku", "Ceza Hukuku", "Tüketici Hukuku", "Gayrimenkul Hukuku", "İcra ve İflas Hukuku", "Arabuluculuk"],
    cv_pubs_h: "Yayınlar",
    cv_pubs: [
      ["Anonim Şirketlerde Esas Sermaye Artırımının Dürüstlük Kuralına Aykırılık Nedeniyle İptali", "On İki Levha Yayıncılık", "Nisan 2018"],
      ["Türk Ticaret Kanununda Hakim Şirketin Kayba Sebebiyet Verici Talimatı/Yöneltmesi ve Bağlı Şirket Yönetim Kurulu Üyelerinin Sorumluluğu", "İstanbul Barosu Dergisi", "Vol.89, 2015/5"],
      ["Usufruct Certificates", "TAD Law Review", "2013/1"],
      ["Acquisition by Joint Stock Companies of Their Own Shares", "TAD Law Review", "2013/1"],
      ["Mergers under the Turkish Commercial Code", "TAD Law Review", "2013/1"],
      ["Are Sharebuybacks by Joint Stock Companies an Alternative to Dividend Distribution?", "10 Dailies", "Vol. III, Issue 11"],
    ],
    cv_toc: ["Hakkımda", "Eğitim", "Üyelikler", "Sertifikalar", "Uzmanlık", "Yayınlar"],

    // Mediation
    med_eyebrow: "Hizmet · 02",
    med_title: "Arabuluculuk",
    med_lede: "Uyuşmazlıkların mahkemeye gitmeden, tarafların kendi iradeleriyle ve bağımsız bir uzman eşliğinde çözüldüğü modern uyuşmazlık çözüm yöntemi.",
    med_pillars: [
      ["Hızlı", "Çoğu uyuşmazlık 3–4 hafta içinde sonuçlanır.", "≤ 4 HAFTA"],
      ["Gizli", "Tüm görüşmeler yasal güvence altında gizlidir.", "KVKK"],
      ["Bağlayıcı", "Anlaşma belgesi mahkeme ilamı niteliğindedir.", "İCRA EDİLEBİLİR"],
    ],
    med_fields_eyebrow: "Çalışma alanları",
    med_fields_title: "Hangi uyuşmazlıklarda arabuluculuk?",
    med_fields: [
      ["Ticari Uyuşmazlıklar", "Şirketler arası alacak, sözleşme ve ticari iş uyuşmazlıklarında dava şartı arabuluculuk."],
      ["İş Hukuku", "İşçi-işveren arasındaki kıdem, ihbar, fazla mesai ve fesih uyuşmazlıkları."],
      ["Tüketici Uyuşmazlıkları", "Tüketici işlemlerinden kaynaklanan uyuşmazlıklarda dava şartı arabuluculuk."],
      ["Aile Hukuku", "Aile içi uyuşmazlıklarda gönüllü arabuluculuk ile uzlaşı temelli çözüm."],
      ["Kira Uyuşmazlıkları", "Kiracı-kiraya veren arasında ortaya çıkan uyuşmazlıklarda dava şartı arabuluculuk."],
      ["Komşuluk Hukuku", "Ortak yaşam alanlarından doğan uyuşmazlıklarda hızlı çözüm."],
    ],
    med_proc_eyebrow: "Süreç",
    med_proc_title: "Nasıl ilerliyor?",
    med_proc: [
      ["Başvuru", "Arabuluculuk merkezine veya doğrudan büromuza başvuru."],
      ["Görüşme", "Tarafların ortak ya da ayrı oturumlarla dinlenmesi."],
      ["Müzakere", "Çıkar temelli müzakere ile ortak çözümün aranması."],
      ["Anlaşma", "Anlaşma belgesinin düzenlenmesi ve icra edilebilirlik şerhi."],
    ],

    // Avukatlık
    law_eyebrow: "Hizmet · 01",
    law_title: "Avukatlık",
    law_lede: "Bireysel ve kurumsal müvekkillerimize geniş bir hukuk yelpazesinde temsil ve danışmanlık. Her dosyayı titizlik, hız ve sonuç odaklılık ilkeleriyle yönetiyoruz.",
    law_practices: [
      ["Aile Hukuku", "Boşanma, velayet, nafaka, mal rejimi, evlat edinme."],
      ["İş Hukuku", "İşçi-işveren uyuşmazlıkları, fesih, kıdem ve ihbar tazminatı."],
      ["Ticaret Hukuku", "Şirketler, sözleşmeler, ticari alacak ve şirket danışmanlığı."],
      ["Gayrimenkul Hukuku", "Tapu iptali, kira, kentsel dönüşüm, kat mülkiyeti."],
      ["İcra & İflas", "Alacak takibi, itirazın iptali, iflas erteleme süreçleri."],
      ["Tüketici Hukuku", "Tüketici hakem heyetleri ve mahkemeleri süreçleri."],
      ["Sözleşmeler", "Sözleşme hazırlama, müzakere ve risk analizi."],
      ["Miras Hukuku", "Vasiyetname, mirasın paylaşımı, tenkis ve iade davaları."],
      ["KVKK & Veri Koruma", "Veri sorumlusu uyumu, VERBİS, politikalar ve aydınlatma."],
    ],
    law_why_eyebrow: "Neden biz",
    law_why_title: "Hukuk birikimi, dijital iş akışı.",
    law_why_text: "Geleneksel hukuk pratiğini modern teknolojilerle birleştiriyoruz. Süreç takibi, belge yönetimi ve raporlamada müvekkillerimize her an şeffaf bir görünürlük sunuyoruz.",
    law_why_pts: [
      ["Şeffaf Ücretlendirme", "Net ücret tarifesi ve önceden açıklanan masraf planı."],
      ["Dijital Müvekkil Paneli", "Dosyanızı her an çevrimiçi takip edebilirsiniz."],
      ["Hızlı İletişim", "WhatsApp, e-posta ve telefonla aynı gün içinde dönüş."],
      ["Çok Dilli Hizmet", "Türkçe ve İngilizce sözleşme yönetimi."],
    ],

    // Calculator
    calc_eyebrow: "Hesap aracı",
    calc_title: "Arabulucu Ücret Hesaplama",
    calc_lede: "1 Ocak 2026 tarihli Arabuluculuk Asgari Ücret Tarifesi'ne göre. Sonuçlar bilgilendirme amaçlıdır; bağlayıcı değildir.",
    calc_dispute: "Uyuşmazlık türü",
    calc_parties: "Taraf sayısı",
    calc_agree: "Anlaşma durumu",
    calc_no_agree: "Anlaşma yok",
    calc_yes_agree: "Anlaşma var",
    calc_amount: "Anlaşma tutarı (TL)",
    calc_amount_hint: "Para ile değerlendirilemeyen uyuşmazlıklarda boş bırakın.",
    calc_consumer: "Tüketici uyuşmazlığı detayları",
    calc_equal: "Eşit ödenecek",
    calc_seller: "Satıcı/Sağlayıcı ödeyecek",
    calc_seller_count: "Satıcı/Sağlayıcı sayısı",
    calc_consumer_count: "Tüketici sayısı",
    calc_compute: "Hesapla",
    calc_reset: "Sıfırla",
    calc_brut: "Brüt ücret (KDV dahil)",
    calc_avg_rate: "Ortalama nisbi oran",
    calc_scenarios: "Senaryolar",
    calc_explain: "Açıklama",
    calc_kademe: "Kademeli hesaplama",
    calc_empty: "Bilgileri girip Hesapla butonuna tıklayın.",
    calc_brut_l: "Brüt", calc_kdv_l: "KDV", calc_stopaj_l: "Stopaj", calc_net_l: "Net Ödeme",
    calc_disclaimer: "* 1 Ocak 2026 tarihli Arabuluculuk Asgari Ücret Tarifesi'ne göredir. Bilgilendirme amaçlıdır; bağlayıcı değildir.",
    parties: [["2 Taraf", 2], ["3–5 Taraf", 3], ["6–10 Taraf", 6], ["11+ Taraf", 11]],
    dispute_types: [
      ["ticari", "Ticari"],
      ["isciIsveren", "İşçi–İşveren"],
      ["kiraOrtaklik", "Kira / Komşuluk / Ortaklık"],
      ["aile", "Aile"],
      ["tuketici", "Tüketici"],
      ["diger", "Diğer"],
    ],

    // Apps
    apps_eyebrow: "Hukuk Teknolojileri",
    apps_title: "Uygulamalar",
    apps_lede: "Hukuk pratiğinin günlük operasyonlarını sadeleştiren araçlar. Arabulucular, avukatlar ve hukuk büroları için pratik, hızlı ve güvenli çözümler.",
    apps_list: [
      ["arabulucu-ofis", "Arabulucu Ofis", "Arabuluculuk dosyalarınızı uçtan uca yönetin. Belge şablonları, oturum takvimi, taraf yönetimi ve raporlama.", "Dosya Yönetimi"],
      ["arabulucu-hesap", "Arabulucu Hesap", "Ücret hesaplaması, asgari tarife uygulamaları ve fatura/serbest meslek makbuzu desteği.", "Mali İşler"],
      ["smm-hesap", "SMM Hesap", "Serbest meslek makbuzu hazırlığı, stopaj ve KDV hesaplamaları ile gelir-gider raporları.", "Muhasebe"],
    ],
    apps_cta: "İhtiyacınıza özel çözüm geliştirelim.",
    apps_cta_sub: "Hukuk büronuzun süreçlerine özel uygulamalar ve otomasyonlar için bizimle iletişime geçin.",

    // Blog
    blog_eyebrow: "Yazılar",
    blog_title: "Notlar ve rehberler",
    blog_lede: "Hukuk, arabuluculuk ve uyuşmazlık çözümü üzerine güncel yazılar.",
    blog_read: "Devamını oku",
    blog_posts: [
      ["arabuluculuk-nedir", "Arabuluculuk Nedir, Nasıl İşler?", "Arabuluculuk sürecinin temel ilkeleri, dava şartı arabuluculuk kapsamı ve süreç adımları.", "2026-04-10", "Arabuluculuk", "8 dk"],
      ["is-hukukunda-fesih", "İş Hukukunda Geçerli ve Haklı Fesih Ayrımı", "İşveren ve işçi açısından fesih türleri, ihbar süreleri ve tazminat hakları.", "2026-03-22", "İş Hukuku", "12 dk"],
      ["ticari-uyusmazlik", "Ticari Uyuşmazlıklarda Arabuluculuk", "Şirketler için arabuluculuğun stratejik avantajları, maliyet ve süre üzerindeki etkileri.", "2026-03-05", "Ticaret Hukuku", "6 dk"],
      ["kvkk-uyumu", "KVKK Uyumu için Şirket Rehberi", "Veri sorumlusu yükümlülükleri, VERBİS kayıt süreçleri ve aydınlatma yükümlülüğü.", "2026-02-12", "KVKK", "10 dk"],
      ["kira-uyusmazliklari", "Kira Uyuşmazlıklarında Yeni Dönem", "Kiracı ve kiraya veren açısından zorunlu arabuluculuk uygulaması ve süreç yönetimi.", "2026-01-28", "Gayrimenkul", "7 dk"],
      ["aile-hukuku-bosanma", "Boşanma Davalarında Bilmeniz Gerekenler", "Anlaşmalı ve çekişmeli boşanma süreçleri, velayet ve mal rejimi konuları.", "2026-01-08", "Aile Hukuku", "9 dk"],
    ],

    // Contact
    ctc_eyebrow: "İletişim",
    ctc_title: "Bize Ulaşın",
    ctc_lede: "Hukuki sorununuz için ücretsiz ön görüşme talep edebilirsiniz. Aynı gün dönüş yapıyoruz.",
    ctc_office: "Ofis",
    ctc_email: "E-posta",
    ctc_ig: "Instagram",
    ctc_hours: "Çalışma Saatleri",
    ctc_form_h: "Randevu Talep Formu",
    ctc_form_sub: "Bilgileriniz gizli tutulur. KVKK kapsamında işlenir.",
    ctc_name: "Ad Soyad", ctc_phone: "Telefon", ctc_emailf: "E-posta", ctc_subject: "Konu", ctc_message: "Mesajınız",
    ctc_submit: "Gönder", ctc_subjects: ["Arabuluculuk", "Avukatlık", "Uygulamalar", "Diğer"],
    ctc_required: "Bu alan zorunludur",
    ctc_invalid_email: "Geçerli bir e-posta girin",
    ctc_invalid_phone: "Geçerli bir telefon girin",
    ctc_sent: "Talebiniz iletildi. En kısa sürede dönüş yapacağız.",

    // Footer
    foot_h_services: "Hizmetler",
    foot_h_firm: "Kurumsal",
    foot_h_contact: "İletişim",
    foot_baro: "İstanbul Barosu üyesidir. Adalet Bakanlığı kayıtlı arabulucu.",
    foot_rights: "Tüm hakları saklıdır.",
  },

  en: {
    appointment: "Book consultation",
    menu: "Menu", close: "Close",

    hero_eyebrow: "Istanbul · Law Practice",
    hero_role: "Attorney & Mediator",
    hero_first: "Av. Arb. Selim",
    hero_last: "Yalçın",
    hero_phrase_pre: "Settle before court;",
    hero_phrase_em: "litigate",
    hero_phrase_post: "with rigor when we must.",
    hero_meta_a: "Bar No.",
    hero_meta_a_v: "Istanbul · 46524",
    hero_meta_b: "Mediator",
    hero_meta_b_v: "MoJ · 26722",
    hero_meta_c: "Located",
    hero_meta_c_v: "Kartal / Istanbul",
    hero_lede: "Modern, results-focused legal counsel for individuals and companies. We resolve disputes before court — and litigate with rigor when we must.",
    hero_cta_primary: "Request consultation",
    hero_cta_secondary: "Practice areas",

    services_eyebrow: "Practice areas",
    services_title: "An approach tailored to every dispute.",
    services_sub: "From family to commercial, employment to consumer law — full-spectrum support.",

    process_eyebrow: "Working method",
    process_title: "Transparent, measured, results-oriented.",

    quote: "“The aim of law is to balance power; the aim of a good lawyer is to clarify the client's voice.”",
    quote_attr: "Selim Yalçın",

    cta_eyebrow: "Get in touch",
    cta_title: "Begin your matter today.",
    cta_sub: "In-person and online consultations — same-day response.",
    cta_primary: "Book consultation",

    cv_eyebrow: "Profile",
    cv_title: "Selim Yalçın",
    cv_subtitle: "Attorney & Mediator · Istanbul Bar Association",
    cv_about_h: "About",
    cv_about: [
      "Graduated from Koç University Law School in 2012; admitted to the bar in 2013.",
      "Registered with the Istanbul Bar Association under No. 46524.",
      "Earned an LL.M. in Private Law from Koç University in 2018, specialising in Commercial Law.",
      "Active practice across Commercial, Family, Obligations, Bankruptcy, and Criminal Law.",
      "Registered as a mediator with the Ministry of Justice (No. 26722) since 2023.",
      "Fluent in English; basic German.",
    ],
    cv_education_h: "Education",
    cv_education: [
      ["Koç University", "LL.M. in Private Law (with thesis)", "2018"],
      ["Koç University", "Faculty of Law", "2012"],
      ["University of Connecticut", "English Language Institute", "2006"],
    ],
    cv_memberships_h: "Memberships",
    cv_memberships: ["Istanbul Bar Association", "Ministry of Justice — Mediation Department"],
    cv_certs_h: "Certifications",
    cv_certs: ["Commercial Law", "Criminal Law", "Family Law", "Obligations Law", "Bankruptcy Law"],
    cv_specs_h: "Areas of expertise",
    cv_specs: ["Commercial Law", "Family Law", "Employment Law", "Criminal Law", "Consumer Law", "Real Estate Law", "Bankruptcy Law", "Mediation"],
    cv_pubs_h: "Publications",
    cv_pubs: [
      ["Annulment of Capital Increase in Joint-Stock Companies for Breach of the Good-Faith Principle", "On İki Levha Publishing", "April 2018"],
      ["Loss-Causing Instructions of the Controlling Company under the TCC and Liability of Subsidiary Directors", "Istanbul Bar Review", "Vol.89, 2015/5"],
      ["Usufruct Certificates", "TAD Law Review", "2013/1"],
      ["Acquisition by Joint Stock Companies of Their Own Shares", "TAD Law Review", "2013/1"],
      ["Mergers under the Turkish Commercial Code", "TAD Law Review", "2013/1"],
      ["Are Share Buybacks an Alternative to Dividend Distribution?", "10 Dailies", "Vol. III, Issue 11"],
    ],
    cv_toc: ["About", "Education", "Memberships", "Certifications", "Expertise", "Publications"],

    med_eyebrow: "Service · 02",
    med_title: "Mediation",
    med_lede: "A modern dispute-resolution method where parties reach their own settlement, supported by an independent expert — without going to court.",
    med_pillars: [
      ["Fast", "Most disputes conclude within 3–4 weeks.", "≤ 4 WEEKS"],
      ["Confidential", "All sessions are confidential under law.", "GDPR/KVKK"],
      ["Binding", "The settlement deed has the force of a court judgment.", "ENFORCEABLE"],
    ],
    med_fields_eyebrow: "Practice areas",
    med_fields_title: "Where mediation applies.",
    med_fields: [
      ["Commercial Disputes", "Mandatory mediation for inter-company receivables, contract and commercial disputes."],
      ["Employment Law", "Severance, notice, overtime and termination disputes."],
      ["Consumer Disputes", "Mandatory mediation for disputes from consumer transactions."],
      ["Family Law", "Voluntary mediation for compromise-based resolution."],
      ["Tenancy Disputes", "Mandatory mediation between landlord and tenant."],
      ["Neighbourhood Law", "Quick resolution for shared-living disputes."],
    ],
    med_proc_eyebrow: "Process",
    med_proc_title: "How it proceeds.",
    med_proc: [
      ["Application", "Application to the mediation centre or directly to our office."],
      ["Hearing", "Joint or separate sessions to hear each party."],
      ["Negotiation", "Interest-based negotiation toward a common solution."],
      ["Settlement", "Drafting of the settlement deed with enforceability annotation."],
    ],

    law_eyebrow: "Service · 01",
    law_title: "Legal Counsel",
    law_lede: "Representation and advisory across a wide legal spectrum for individuals and corporates. Each matter handled with rigor, speed, and a focus on outcomes.",
    law_practices: [
      ["Family Law", "Divorce, custody, alimony, marital regime, adoption."],
      ["Employment Law", "Employee–employer disputes, termination, severance and notice."],
      ["Commercial Law", "Companies, contracts, receivables, corporate advisory."],
      ["Real Estate Law", "Title cancellation, leases, urban renewal, condominium."],
      ["Bankruptcy Law", "Receivable enforcement, objection, bankruptcy postponement."],
      ["Consumer Law", "Consumer arbitration boards and courts."],
      ["Contracts", "Contract drafting, negotiation, risk analysis."],
      ["Inheritance Law", "Wills, probate, reduction and restitution actions."],
      ["Data Protection", "Controller compliance, registry, policies."],
    ],
    law_why_eyebrow: "Why us",
    law_why_title: "Legal depth, digital workflow.",
    law_why_text: "We pair traditional legal practice with modern technology — full transparency on case progress, documents and reporting, anytime.",
    law_why_pts: [
      ["Transparent fees", "Clear fee schedule and pre-disclosed cost plan."],
      ["Client portal", "Track your file online at any time."],
      ["Fast contact", "Same-day response on WhatsApp, email, phone."],
      ["Bilingual", "Contract management in Turkish and English."],
    ],

    calc_eyebrow: "Calculator",
    calc_title: "Mediator Fee Calculator",
    calc_lede: "Per the Mediation Minimum Fee Tariff dated 1 January 2026. Informational only — non-binding.",
    calc_dispute: "Dispute type",
    calc_parties: "Number of parties",
    calc_agree: "Settlement status",
    calc_no_agree: "No settlement",
    calc_yes_agree: "Settled",
    calc_amount: "Settlement amount (TRY)",
    calc_amount_hint: "Leave blank for non-monetary disputes.",
    calc_consumer: "Consumer dispute details",
    calc_equal: "Split equally",
    calc_seller: "Seller pays",
    calc_seller_count: "Seller/Provider count",
    calc_consumer_count: "Consumer count",
    calc_compute: "Calculate",
    calc_reset: "Reset",
    calc_brut: "Gross fee (incl. VAT)",
    calc_avg_rate: "Avg. rate",
    calc_scenarios: "Scenarios",
    calc_explain: "Notes",
    calc_kademe: "Tiered breakdown",
    calc_empty: "Fill in details and press Calculate.",
    calc_brut_l: "Gross", calc_kdv_l: "VAT", calc_stopaj_l: "Withhold.", calc_net_l: "Net",
    calc_disclaimer: "* Per the 1 January 2026 Mediation Minimum Fee Tariff. Informational only.",
    parties: [["2 Parties", 2], ["3–5 Parties", 3], ["6–10 Parties", 6], ["11+ Parties", 11]],
    dispute_types: [
      ["ticari", "Commercial"],
      ["isciIsveren", "Employment"],
      ["kiraOrtaklik", "Tenancy / Neighbour / Partition"],
      ["aile", "Family"],
      ["tuketici", "Consumer"],
      ["diger", "Other"],
    ],

    apps_eyebrow: "Legal Technology",
    apps_title: "Applications",
    apps_lede: "Tools that simplify the daily operations of legal practice. Practical, fast and secure for mediators, attorneys and law offices.",
    apps_list: [
      ["arabulucu-ofis", "Mediator Office", "Manage mediation files end-to-end. Templates, schedules, party tracking and reports.", "File mgmt."],
      ["arabulucu-hesap", "Mediator Accounting", "Fee calculation, tariff application, invoicing and SMM receipt support.", "Finance"],
      ["smm-hesap", "SMM Receipt", "Self-employment receipt prep, withholding & VAT, P&L reports.", "Bookkeeping"],
    ],
    apps_cta: "Let's build a tool tailored to your firm.",
    apps_cta_sub: "Get in touch for custom apps and automation built around your processes.",

    blog_eyebrow: "Notes",
    blog_title: "Notes & guides",
    blog_lede: "Current writings on law, mediation and dispute resolution.",
    blog_read: "Read",
    blog_posts: [
      ["arabuluculuk-nedir", "What Is Mediation, How Does It Work?", "Core principles of mediation, mandatory scope and process steps.", "2026-04-10", "Mediation", "8 min"],
      ["is-hukukunda-fesih", "Valid vs Just-Cause Termination in Employment Law", "Termination types, notice periods and severance from both sides.", "2026-03-22", "Employment", "12 min"],
      ["ticari-uyusmazlik", "Mediation in Commercial Disputes", "Strategic advantages of mediation for companies — cost and time impact.", "2026-03-05", "Commercial", "6 min"],
      ["kvkk-uyumu", "Corporate Guide to Data Protection Compliance", "Controller obligations, registry steps and disclosure duties.", "2026-02-12", "Data", "10 min"],
      ["kira-uyusmazliklari", "A New Era for Tenancy Disputes", "Mandatory mediation for tenants and landlords; process management.", "2026-01-28", "Real Estate", "7 min"],
      ["aile-hukuku-bosanma", "What to Know About Divorce Cases", "Mutual and contested divorce, custody and marital regime.", "2026-01-08", "Family", "9 min"],
    ],

    ctc_eyebrow: "Contact",
    ctc_title: "Get in touch",
    ctc_lede: "Request a free initial consultation. We respond the same day.",
    ctc_office: "Office", ctc_email: "Email", ctc_ig: "Instagram", ctc_hours: "Hours",
    ctc_form_h: "Consultation Request", ctc_form_sub: "Information is kept confidential under data-protection law.",
    ctc_name: "Full name", ctc_phone: "Phone", ctc_emailf: "Email", ctc_subject: "Subject", ctc_message: "Message",
    ctc_submit: "Send",
    ctc_subjects: ["Mediation", "Legal counsel", "Applications", "Other"],
    ctc_required: "This field is required",
    ctc_invalid_email: "Enter a valid email",
    ctc_invalid_phone: "Enter a valid phone",
    ctc_sent: "Request sent. We'll be in touch shortly.",

    foot_h_services: "Services", foot_h_firm: "Firm", foot_h_contact: "Contact",
    foot_baro: "Member of Istanbul Bar Association · MoJ-registered mediator.",
    foot_rights: "All rights reserved.",
  },
};
